=== dnhmnn/mpg/referenz/naep/xsd/naep-daten.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:d="http://naep.divi.de/daten"
           xmlns:std="http://naep.divi.de/strukturen/std"
           xmlns:red="http://naep.divi.de/meta/redaktionell"
           targetNamespace="http://naep.divi.de/daten"
           elementFormDefault="qualified">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://naep.divi.de/strukturen/std"
               schemaLocation="naep-strukturen-std.xsd"/>
    
    <xs:element name="naep">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="version" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="protokoll" type="xs:token" use="required"/>
                        <xs:attribute name="metamodell" type="xs:token" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abschnitte" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="d:abs" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="schemaVersion" type="xs:token" use="required" fixed="1.0"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="abs" type="d:TypAbschnitt"/>
    
    <xs:complexType name="TypAbschnitt">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element name="nb"/>
                <xs:sequence>
                    <xs:group ref="d:GrAbschnitt" minOccurs="1" maxOccurs="1"/>
                    <xs:element ref="d:abs" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:element ref="d:abs" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="d:AGrCodeAsId"/>
    </xs:complexType>
    
    <xs:group name="GrAbschnitt">
        <xs:choice>
            <xs:element name="dat" type="d:TypDaten"/>
            <xs:element name="ver" type="d:TypVerlauf"/>
            <xs:element name="leer">
                <xs:complexType>
                    <xs:attributeGroup ref="d:AGrCodeAsId"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    
    <xs:complexType name="TypDaten">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:sequence>
                    <xs:group ref="d:GrEingabe" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="sonst" type="d:TypSonstiges" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:element name="sonst" type="d:TypSonstiges" minOccurs="1" maxOccurs="1"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TypLeer">
        <xs:attribute name="a" type="d:TypCode" use="optional"/>
        <xs:attribute name="g" type="d:TypCode" use="optional"/>
        <xs:attributeGroup ref="d:AGrCode"/>
    </xs:complexType>
    
    <xs:complexType name="TypVerlauf">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element name="leer">
                    <xs:complexType>
                        <xs:attributeGroup ref="d:AGrCode"/>
                    </xs:complexType>
                </xs:element>
                <xs:sequence>
                    <xs:element name="r" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="d:GrEingabe" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="d:AGrCodeAsId"/>
    </xs:complexType>
    
    <xs:complexType name="TypFrage">
        <xs:attribute name="f" type="d:TypCode" use="required"/>
        <xs:attribute name="w" type="std:TypAntwort" use="required"/>
    </xs:complexType>
    
    <xs:group name="GrEingabe">
        <xs:choice>
            <xs:element name="wrt" type="d:TypFeld"/>
            <xs:element name="sel" type="d:TypAuswahl">
                <xs:unique name="selektiert">
                    <xs:selector xpath="d:selektiert"/>
                    <xs:field xpath="@code"/>
                </xs:unique>
            </xs:element>
            <xs:element name="leer" type="d:TypLeer"/>
            <xs:element name="sonst" type="d:TypSonstiges"/>
            <xs:element name="ant" type="d:TypFrage"/>
            <xs:element name="txt">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="z" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attributeGroup ref="d:AGrCode"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="str" type="d:TypStrukturiert"/>
        </xs:choice>
    </xs:group>
    
    <xs:complexType name="TypAuswahl">
        <xs:attribute name="a" type="d:TypCode" use="required"/>
        <xs:attribute name="o" type="d:TypCode" use="required"/>
        <xs:attribute name="n" type="xs:decimal" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="TypStrukturiert">
        <xs:sequence>
            <xs:element name="e" type="std:TypStrukturiertBase" minOccurs="1" maxOccurs="1"/>
            <xs:group ref="d:GrEingabe" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="d:AGrCode"/>
    </xs:complexType>
    
    <xs:complexType name="TypSonstiges">
        <xs:attributeGroup ref="d:AGrCode"/>
        <xs:attribute name="t" type="std:TypText" use="required"/>
        <xs:attribute name="a" type="d:TypCode" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="TypFeld">
        <xs:attribute name="f" type="d:TypCode" use="required"/>
        <xs:attribute name="d" type="d:TypDatum" use="optional"/>
        <xs:attribute name="z" type="std:TypZeit" use="optional"/>
        <xs:attribute name="t" type="std:TypText" use="optional"/>
        <xs:attribute name="n" type="xs:decimal" use="optional"/>
        <xs:attribute name="e" type="std:TypText" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="TypEinheit">
        <xs:list itemType="xs:string">
        </xs:list>
    </xs:simpleType>
    
    <xs:simpleType name="TypDatum">
        <xs:restriction base="xs:date">
            <xs:pattern value="([0-9]{4})-([0-9]{2})-([0-9]{2})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TypId">
        <xs:restriction base="xs:ID">
            <xs:minLength value="3"/>
            <xs:maxLength value="6"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TypCode">
        <xs:restriction base="xs:token">
            <xs:minLength value="3"/>
            <xs:maxLength value="6"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:attributeGroup name="AGrCode">
        <xs:attribute name="c" type="d:TypCode" use="required"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="AGrCodeAsId">
        <xs:attribute name="c" type="d:TypId" use="required"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="AGrCodeTerm">
        <xs:attributeGroup ref="d:AGrCode"/>
        <xs:attribute name="term" type="std:TypText" use="required"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="AGrCodeOptTerm">
        <xs:attributeGroup ref="d:AGrCode"/>
        <xs:attribute name="term" type="std:TypText"/>
    </xs:attributeGroup>
    
</xs:schema>

=== dnhmnn/mpg/referenz/naep/beispiele/bsp-nicht-bearbeitet-daten.xml
<?xml version="1.0" encoding="UTF-8"?>
<dt:naep xsi:schemaLocation="http://naep.divi.de/daten ../xsd/naep-daten.xsd http://naep.divi.de/strukturen/std ../xsd/naep-strukturen-std.xsd" schemaVersion="1.0" xmlns:std="http://naep.divi.de/strukturen/std" xmlns:dt="http://naep.divi.de/daten" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://naep.divi.de/dokument">
    <dt:version protokoll="V.6.0-0.93-NoVar-130820" metamodell="1.0"/>
    <dt:abschnitte>
        <dt:abs c="A01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="B01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="C01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="D01">
            <dt:abs c="D08">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="DDU">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="DHX">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="DL8">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="DOC">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="DQH">
                <dt:nb/>
            </dt:abs>
        </dt:abs>
        <dt:abs c="E01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="F01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="G01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="H01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="I01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="J01">
            <dt:abs c="J08">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="J3J">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="J8L">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="JB4">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="JE8">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="JGR">
                <dt:nb/>
            </dt:abs>
        </dt:abs>
        <dt:abs c="K01">
            <dt:nb/>
        </dt:abs>
        <dt:abs c="L01">
            <dt:abs c="L08">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="L4B">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="L7M">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="LAQ">
                <dt:nb/>
            </dt:abs>
        </dt:abs>
        <dt:abs c="M01">
            <dt:abs c="M08">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="M4W">
                <dt:nb/>
            </dt:abs>
            <dt:abs c="M87">
                <dt:nb/>
            </dt:abs>
        </dt:abs>
    </dt:abschnitte>
</dt:naep>

=== dnhmnn/mpg/referenz/naep/beispiele/bsp-leer-daten.xml
<?xml version="1.0" encoding="UTF-8"?>
<dt:naep xsi:schemaLocation="http://naep.divi.de/daten ../xsd/naep-daten.xsd http://naep.divi.de/strukturen/std ../xsd/naep-strukturen-std.xsd" schemaVersion="1.0" xmlns:std="http://naep.divi.de/strukturen/std" xmlns:dt="http://naep.divi.de/daten" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://naep.divi.de/dokument">
    <dt:version protokoll="V.6.0-0.93-NoVar-130820" metamodell="1.0"/>
    <dt:abschnitte>
        <dt:abs c="A01">
            <dt:dat>
                <dt:str c="A08">
                    <dt:e xsi:type="std:PatStammdaten">
                        <std:Patient pseudonym="ja">
                            <std:Name>Mustermann</std:Name>
                            <std:Vorname>Heinz</std:Vorname>
                            <std:GebDat>1970-10-10</std:GebDat>
                        </std:Patient>
                        <std:Adresse>
                            <std:Strasse>Musterstr. 10</std:Strasse>
                            <std:PLZ>11111</std:PLZ>
                            <std:Ort>Musterstadt</std:Ort>
                        </std:Adresse>
                        <std:Versicherung>
                            <std:Kasse nr="123456789">MUSTERKASSE</std:Kasse>
                            <std:VersNr>987654321</std:VersNr>
                        </std:Versicherung>
                    </dt:e>
                    <dt:leer a="A0F" c="A0M"/>
                    <dt:sel a="A17" o="A1E"/>
                    <dt:leer g="A1S" c="A1Z"/>
                </dt:str>
            </dt:dat>
        </dt:abs>
        <dt:abs c="B01">
            <dt:dat>
                <dt:str c="B08">
                    <dt:e xsi:type="std:EinsatztechnischeDaten">
                        <std:EinsatzNr>111111111</std:EinsatzNr>
                        <std:PatNr>222222222</std:PatNr>
                        <std:PersNr>3333333333</std:PersNr>
                        <std:Standort>Musterstandort</std:Standort>
                        <std:LeitstelleKFZ>MU</std:LeitstelleKFZ>
                    </dt:e>
                </dt:str>
                <dt:wrt f="B0F" d="2015-10-20"/>
                <dt:str c="B0M">
                    <dt:e xsi:type="std:Einsatzort">
                    </dt:e>
                    <dt:sel a="B0T" o="B10"/>
                </dt:str>
                <dt:sel a="B3J" o="B3Q"/>
                <dt:wrt f="B6U" t="TEXT TEXT"/>
                <dt:wrt f="B80" t="TEXT TEXT"/>
                <dt:wrt f="BAJ" t="TEXT TEXT"/>
                <dt:wrt f="BBP" t="TEXT TEXT"/>
                <dt:wrt f="BBW" t="TEXT TEXT"/>
                <dt:sel a="BC3" o="BCA"/>
                <dt:wrt f="BEF" z="13:00"/>
                <dt:ant f="BET" w="J"/>
                <dt:wrt f="BF0" z="13:00"/>
                <dt:wrt f="BF7" z="13:00"/>
                <dt:wrt f="BFE" z="13:00"/>
                <dt:wrt f="BFS" z="13:00"/>
                <dt:wrt f="BFZ" z="13:00"/>
                <dt:wrt f="BG6" z="13:00"/>
                <dt:wrt f="BGD" z="13:00"/>
            </dt:dat>
        </dt:abs>
        <dt:abs c="C01">
            <dt:dat>
                <dt:txt c="C08">
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                </dt:txt>
                <dt:sel a="C0F" o="C0M"/>
                <dt:leer a="C1L" c="C1S"/>
                <dt:ant f="C2D" w="J"/>
                <dt:wrt f="C2K" z="13:00"/>
                <dt:ant f="C2R" w="J"/>
                <dt:sel a="C2Y" o="C35"/>
            </dt:dat>
        </dt:abs>
        <dt:abs c="D01">
            <dt:abs c="D08">
                <dt:leer c="D0F"/>
            </dt:abs>
            <dt:abs c="DDU">
                <dt:leer c="DE1"/>
            </dt:abs>
            <dt:abs c="DHX">
                <dt:leer c="DI4"/>
            </dt:abs>
            <dt:abs c="DL8">
                <dt:leer c="DLF"/>
            </dt:abs>
            <dt:abs c="DOC">
                <dt:leer c="DOJ"/>
            </dt:abs>
            <dt:abs c="DQH">
                <dt:leer c="DQO"/>
            </dt:abs>
        </dt:abs>
        <dt:abs c="E01">
            <dt:leer c="E08"/>
        </dt:abs>
        <dt:abs c="F01">
            <dt:leer c="F08"/>
        </dt:abs>
        <dt:abs c="G01">
            <dt:dat>
                <dt:txt c="G08">
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                    <dt:z>TEXT TEXT TEXT</dt:z>
                </dt:txt>
                <dt:sel a="G0F" o="G0M"/>
                <dt:ant f="G26" w="J"/>
            </dt:dat>
        </dt:abs>
        <dt:abs c="H01">
            <dt:ver c="H08">
                <dt:leer c="H0F"/>
            </dt:ver>
        </dt:abs>
        <dt:abs c="I01">
            <dt:leer c="I08"/>
        </dt:abs>
        <dt:abs c="J01">
            <dt:abs c="J08">
                <dt:dat>
                    <dt:sel a="J0F" o="J0M"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="J3J">
                <dt:dat>
                    <dt:sel a="J3Q" o="J3X"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="J8L">
                <dt:dat>
                    <dt:sel a="J8S" o="J8Z"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="JB4">
                <dt:dat>
                    <dt:sel a="JBB" o="JBI"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="JE8">
                <dt:dat>
                    <dt:sel a="JEF" o="JEM"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="JGR">
                <dt:dat>
                    <dt:ant f="JGY" w="J"/>
                    <dt:sel a="JH5" o="JHC"/>
                    <dt:sel a="JJV" o="JK2"/>
                    <dt:sel a="JL8" o="JLF"/>
                    <dt:sel a="JM0" o="JM7"/>
                    <dt:sel a="JN6" o="JND"/>
                    <dt:sonst c="JNR" t="TEXT TEXT TEXT"/>
                </dt:dat>
            </dt:abs>
        </dt:abs>
        <dt:abs c="K01">
            <dt:dat>
                <dt:sel a="K08" o="K0F"/>
                <dt:ant f="K44" w="J"/>
                <dt:ant f="K4B" w="J"/>
                <dt:sel a="K4I" o="K4P"/>
                <dt:wrt f="K5H" z="13:00"/>
            </dt:dat>
        </dt:abs>
        <dt:abs c="L01">
            <dt:abs c="L08">
                <dt:leer c="L0F"/>
            </dt:abs>
            <dt:abs c="L4B">
                <dt:leer c="L4I"/>
            </dt:abs>
            <dt:abs c="L7M">
                <dt:leer c="L7T"/>
            </dt:abs>
            <dt:abs c="LAQ">
                <dt:leer c="LAX"/>
            </dt:abs>
        </dt:abs>
        <dt:abs c="M01">
            <dt:abs c="M08">
                <dt:dat>
                    <dt:sel a="M0F" o="M0M"/>
                    <dt:sel a="M3C" o="M3J"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="M4W">
                <dt:dat>
                    <dt:leer a="M53" c="M5A"/>
                </dt:dat>
            </dt:abs>
            <dt:abs c="M87">
                <dt:dat>
                    <dt:txt c="M8E">
                        <dt:z>TEXT TEXT TEXT</dt:z>
                        <dt:z>TEXT TEXT TEXT</dt:z>
                        <dt:z>TEXT TEXT TEXT</dt:z>
                        <dt:z>TEXT TEXT TEXT</dt:z>
                    </dt:txt>
                </dt:dat>
            </dt:abs>
        </dt:abs>
    </dt:abschnitte>
</dt:naep>
