=== dnhmnn/mpg/referenz/naep/xsd/naep-meta.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:m="http://naep.divi.de/meta"
           xmlns:red="http://naep.divi.de/meta/redaktionell"
           targetNamespace="http://naep.divi.de/meta"
           elementFormDefault="qualified">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="http://www.w3.org/2001/03/xml.xsd" />
    
    <xs:element name="Metamodell">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Protokoll" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="version" type="xs:token" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="m:Definitionen" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Abschnitte" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="m:Abschnitt" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:token" use="required"/>
            <xs:attribute name="schemaVersion" type="xs:token" use="required" fixed="1.0"/>
        </xs:complexType>
        <xs:key name="FrageTyp">
            <xs:selector xpath="m:Definitionen/m:Fragen/m:Typ"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="RefFrageTyp" refer="m:FrageTyp">
            <xs:selector xpath=".//m:Frage"/>
            <xs:field xpath="@typ"/>
        </xs:keyref>
    </xs:element>
    
    <xs:element name="Definitionen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Fragen">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Antwort" type="m:TypCodeTerm" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="Typ" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Antwort" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="code" type="xs:token"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:token" use="required"/>
                                    <xs:attribute name="optional" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token">
                                                <xs:enumeration value="ja"/>
                                                <xs:enumeration value="nein"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Abschnitt" type="m:TypAbschnitt"/>
    
    <xs:complexType name="TypAbschnitt">
        <xs:sequence>
            <xs:element name="Titel" type="xs:string" maxOccurs="1"/>
            <xs:element name="Hinweis" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="Formular" type="m:TypFormular"/>
                <xs:element name="Verlauf" type="m:TypVerlauf"/>
                <xs:element ref="m:Abschnitt" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:any namespace="http://naep.divi.de/meta/redaktionell" processContents="lax" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="m:AGrCode"/>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>
    
    <xs:complexType name="TypFormular">
        <xs:sequence>
            <xs:element name="leer" type="m:TypCodeTerm" minOccurs="0" maxOccurs="unbounded"/>
            <xs:group ref="m:GrEingabe" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Sonstiges" type="m:TypSonstiges" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TypVerlauf">
        <xs:sequence>
            <xs:element name="leer" type="m:TypCodeTerm" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Reihe">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="m:GrEingabe" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="Sonstiges" type="m:TypSonstiges" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="m:AGrCode"/>
    </xs:complexType>
    
    <xs:complexType name="TypFrage">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="wenn-ja" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:choice minOccurs="1" maxOccurs="unbounded">
                                    <xs:element name="Zusatz" type="m:TypZusatz"/>
                                    <xs:group ref="m:GrEingabe"/>
                                </xs:choice>
                                <xs:element name="Sonstiges" type="m:TypSonstiges" minOccurs="0" maxOccurs="1"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Hinweis" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attributeGroup ref="m:AGrFrageTyp"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:group name="GrEingabe">
        <xs:choice>
            <xs:element name="Gruppe" type="m:TypGruppe"/>
            <xs:element name="Feld" type="m:TypFeld"/>
            <xs:element name="Auswahl" type="m:TypAuswahl"/>
            <xs:element name="Auswahlgruppe" type="m:TypAuswahlgruppe"/>
            <xs:element name="Frage" type="m:TypFrage"/>
            <xs:element name="oder" type="m:TypOder"/>
            <xs:element name="Freitext">
                <xs:complexType>
                    <xs:attributeGroup ref="m:AGrCode"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Struktur" type="m:TypStrukturiert"/>
        </xs:choice>
    </xs:group>
    
    <xs:complexType name="TypOder">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="leer" type="m:TypCodeTerm" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:group ref="m:GrEingabe" minOccurs="2" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypGruppe">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:group ref="m:GrEingabe" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypAuswahl">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="leer" type="m:TypCodeTerm" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="Option" type="m:TypOption" maxOccurs="unbounded"/>
                    <xs:element name="Sonstiges" type="m:TypSonstiges" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Zusatz" type="m:TypZusatz" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attributeGroup ref="m:AGrAuswahlTyp"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypStrukturiert">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="xsi" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:attribute name="schemaLocation" use="required">
                                <xs:simpleType>
                                    <xs:list itemType="xs:string"/>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="type" use="required"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Zusatz" type="m:TypZusatz" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypZusatz">
        <xs:sequence>
            <xs:group ref="m:GrEingabe" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="m:AGrAuswahlTyp"/>
    </xs:complexType>
    
    <xs:attributeGroup name="AGrCode">
        <xs:attribute name="code" type="xs:ID"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="AGrAuswahlTyp">
        <xs:attribute name="typ" default="einfach">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="einfach"/>
                    <xs:enumeration value="mehrfach"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="AGrFrageTyp">
        <xs:attribute name="typ" use="required" type="xs:token"/>
    </xs:attributeGroup>
    
    <xs:complexType name="TypSonstiges">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm"/>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypAuswahlgruppe">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="Auswahl" type="m:TypCodeTerm" maxOccurs="unbounded"/>
                    <xs:element name="Optionen">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="leer" type="m:TypCodeTerm" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element name="Option" type="m:TypOption" maxOccurs="unbounded"/>
                                <xs:element name="Zusatz" type="m:TypZusatz" minOccurs="0" maxOccurs="1"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypOption">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="Zusatz" type="m:TypZusatz" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="numerisch" type="xs:integer" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypFeld">
        <xs:complexContent>
            <xs:extension base="m:TypEingabe">
                <xs:sequence>
                    <xs:element name="Zusatz" type="m:TypZusatz" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="typ" type="xs:string" use="required"/>
                <xs:attribute name="einheit" type="xs:string" use="optional"/>
                <xs:attribute name="min" type="xs:double" use="optional"/>
                <xs:attribute name="max" type="xs:double" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypEingabe">
        <xs:complexContent>
            <xs:extension base="m:TypCodeTerm">
                <xs:sequence>
                    <xs:element name="Hinweis" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TypCodeTerm">
        <xs:attributeGroup ref="m:AGrCode"/>
        <xs:attribute name="term" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="TypEinheit">
        <xs:list itemType="xs:string">
        </xs:list>
    </xs:simpleType>
    
    <xs:simpleType name="TypId">
        <xs:restriction base="xs:ID">
            <xs:minLength value="3"/>
            <xs:maxLength value="6"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== dnhmnn/mpg/referenz/naep/naep-metamodell-6.0-1.00-NoVar-01012021.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Metamodell xmlns="http://naep.divi.de/meta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://naep.divi.de/meta ../xsd/naep-meta.xsd" schemaVersion="1.0" version="1.0">
	<Protokoll version="V.6.0-1.00-NoVar-01012021" />
	<Definitionen>
		<Fragen>
			<Antwort code="J" term="ja" />
			<Antwort code="N" term="nein" />
			<Antwort code="UB" term="unbekannt" />
			<Typ name="j_opt" optional="ja">
				<Antwort code="J" />
			</Typ>
			<Typ name="j-n" optional="nein">
				<Antwort code="J" />
				<Antwort code="N" />
			</Typ>
			<Typ name="j-n_opt" optional="ja">
				<Antwort code="J" />
				<Antwort code="N" />
			</Typ>
			<Typ name="j-n-ub" optional="nein">
				<Antwort code="J" />
				<Antwort code="N" />
				<Antwort code="UB" />
			</Typ>
		</Fragen>
	</Definitionen>
	<Abschnitte>
		<Abschnitt code="A01">
			<Titel>
				Patient - Stammdaten
			</Titel>
			<Formular>
				<Struktur code="A08">
					<xsi schemaLocation="http://naep.divi.de/strukturen/std naep-strukturen-std.xsd" type="PatStammdaten" />
					<Zusatz typ="einfach">
						<Auswahl code="A0F" term="Geschlecht" typ="einfach">
							<leer code="A0M" term="unbekannt" />
							<Option code="A0T" term="männlich" />
							<Option code="A10" term="weiblich" />
							<Option code="A11" term="divers" />
						</Auswahl>
						<Auswahl code="A17" term="BMI" typ="einfach">
							<Option code="A1E" term="&lt;=40" />
							<Option code="A1L" term="&gt;40" />
						</Auswahl>
						<oder code="A1S" term="Alter">
							<leer code="A1Z" term="unbekannt" />
							<Feld code="A26" einheit="Jahre" typ="Zahl" />
							<Auswahl code="A2D" typ="einfach">
								<Option code="A2K" term="1-7 Tage" />
								<Option code="A2R" term="8-28 Tage" />
							</Auswahl>
						</oder>
					</Zusatz>
				</Struktur>
			</Formular>
		</Abschnitt>
		<Abschnitt code="B01">
			<Titel>
				Einsatztechnische Daten
			</Titel>
			<Formular>
				<Struktur code="B08">
					<xsi schemaLocation="http://naep.divi.de/strukturen/std naep-strukturen-std.xsd" type="EinsatztechnischeDaten"/>
				</Struktur>
				<Feld code="B0F" term="Einsatz-Datum" typ="Datum" />
				<Struktur code="B0M" term="Einsatz-Ort">
					<xsi schemaLocation="http://naep.divi.de/strukturen/std naep-strukturen-std.xsd" type="Einsatzort"/>
					<Zusatz typ="einfach">
						<Auswahl code="B0T" typ="einfach">
							<Option code="B10" term="Wohnung" />
							<Option code="B17" term="Arztpraxis" />
							<Option code="B1E" term="öff. Raum" />
							<Option code="B1L" term="Bildungseinrichtung" />
							<Option code="B1S" term="Altenheim" />
							<Option code="B1Z" term="Krankenhaus" />
							<Option code="B26" term="Straße" />
							<Option code="B2D" term="Massenveranstaltung" />
							<Option code="B2K" term="Arbeitsplatz" />
							<Option code="B2R" term="Geburtshaus" />
							<Option code="B2Y" term="Schule" />
							<Option code="B35" term="Sportstätte" />
							<Sonstiges code="B3C" term="Sonstige" />
						</Auswahl>
					</Zusatz>
				</Struktur>
				<Auswahl code="B3J" term="Einsatz-Art" typ="einfach">
					<Option code="B3Q" term="Primäreinsatz" />
					<Option code="B3X" term="Folgeeinsatz" />
					<Option code="B44" term="Fehleinsatz">
						<Zusatz typ="einfach">
							<oder code="B4B">
								<Auswahl code="B4I" typ="einfach">
									<Option code="B4P" term="kein Patient" />
									<Option code="B4W" term="Pat. bereits abtransportiert" />
									<Option code="B53" term="abbestellt" />
									<Option code="B5A" term="böswillige Alarmierung" />
								</Auswahl>
								<Auswahl code="B5H" term="Einsatzabbruch" typ="einfach">
									<Option code="B5O" term="technische Gründe" />
									<Option code="B5V" term="Wetter" />
									<Sonstiges code="B62" term="Sonstige" />
								</Auswahl>
							</oder>
						</Zusatz>
					</Option>
					<Option code="B69" term="Notarzt-Nachforderung" />
					<Option code="B6G" term="Sekundäreinsatz z.B. Verlegung" />
					<Option code="B6N" term="vorsorgliche Bereitstellung" />
				</Auswahl>
				<Feld code="B6U" term="Transportziel" typ="Text">
					<Zusatz typ="einfach">
						<Frage code="B71" term="Voranmeldung" typ="j_opt">
							<wenn-ja>
								<Auswahl code="B78" typ="einfach">
									<Option code="B7F" term="Stroke Unit" />
									<Option code="B7M" term="Herzkatheter" />
									<Option code="B7T" term="Traumazentrum" />
								</Auswahl>
							</wenn-ja>
						</Frage>
					</Zusatz>
				</Feld>
				<Feld code="B80" term="Notarzt (Name)" typ="Text">
					<Zusatz typ="einfach">
						<Auswahl code="B87" term="Qualifikation" typ="einfach">
							<Option code="B8E" term="Arzt in Weiterb." />
							<Option code="B8L" term="Facharzt">
								<Zusatz typ="einfach">
									<Auswahl code="B8S" term="Qualifikation" typ="mehrfach">
										<Option code="B8Z" term="Anästhesie" />
										<Option code="B96" term="Chirurgie" />
										<Option code="B9D" term="Innere" />
										<Option code="B9K" term="Pädiatrie" />
										<Option code="B9R" term="Neurologie" />
										<Option code="B9Y" term="Allg. Medizin" />
										<Option code="B9Z" term="Klinische Akutmedizin" />
										<Option code="BA5" term="Zusatz Intensiv" />
										<Option code="BAC" term="Andere" />
									</Auswahl>
								</Zusatz>
							</Option>
						</Auswahl>
					</Zusatz>
				</Feld>
				<Feld code="BAJ" term="Assistenz" typ="Text">
					<Zusatz typ="einfach">
						<Auswahl code="BAQ" term="Höchste Qualifikation" typ="einfach">
							<Option code="BAX" term="Rett.Ass." />
							<Option code="BB4" term="Rett.San." />
							<Option code="BBB" term="Notfalll San." />
							<Option code="BBI" term="(Int.)Pfleg." />
						</Auswahl>
					</Zusatz>
				</Feld>
				<Feld code="BBP" term="RTW-Team" typ="Text" />
				<Feld code="BBW" term="Rufname eigenes Fahrzeug" typ="Text">
					<Hinweis>
						als "eigenes Fahrzeug" wird hier das den Notarzt zubringende (nicht das den Patienten schlusendlich transportierende) Rettungsmitel dokumentiert
					</Hinweis>
				</Feld>
				<Auswahl code="BC3" term="Beteiligte Rettungsmittel" typ="mehrfach">
					<Option code="BCA" term="NEF">
						<Zusatz typ="einfach">
							<Frage code="BCH" term="Selbstfahrer" typ="j_opt" />
						</Zusatz>
					</Option>
					<Option code="BCO" term="NAW" />
					<Option code="BCV" term="RTW" />
					<Option code="BD2" term="KTW" />
					<Option code="BD9" term="RTH" />
					<Option code="BDG" term="ITH" />
					<Option code="BDN" term="Bergrettung" />
					<Option code="TNA" term="TeleNA" />
					<Option code="BDU" term="Wasserrettung" />
					<Sonstiges code="BE1" term="Sonstige" />
				</Auswahl>
				<oder code="BE8">
					<Feld code="BEF" term="Symptom-Beginn" typ="Zeit" />
					<Frage code="BEM" term="vor über 24h" typ="j_opt" />
				    <Frage code="BUK" term="unbekannt" typ="j_opt" />
				</oder>
				<Frage code="BET" term="Kollaps beobachtet" typ="j_opt" />
				<Feld code="BF0" term="Alarm" typ="Zeit" />
				<Feld code="BF7" term="Ankunft (Einsatzort)" typ="Zeit" />
				<Feld code="BFE" term="Ankunft (am Pat.)" typ="Zeit">
					<Zusatz typ="einfach">
						<Frage code="BFL" term="vor Rettungsdienst" typ="j_opt" />
					</Zusatz>
				</Feld>
				<Feld code="BFS" term="Abfahrt" typ="Zeit" />
				<Feld code="BFZ" term="Übergabe" typ="Zeit" />
				<Feld code="BG6" term="Einsatzbereit" typ="Zeit" />
				<Feld code="BGD" term="Ende" typ="Zeit" />
			</Formular>
		</Abschnitt>
		<Abschnitt code="C01">
			<Titel>
				Notfallgeschehen, Anamnese, Erstbefund, Vormedikation, Vorbehandlung
			</Titel>
			<Formular>
				<Freitext code="C08" />
				<Auswahl code="C0F" term="AZ des Pat. vor dem Ereignis (entspr. ASA)" typ="einfach">
					<Option code="C0M" term="gesund" />
					<Option code="C0T" term="leicht eingeschränkt" />
					<Option code="C10" term="deutlich eingeschränkt" />
					<Option code="C1E" term="akut lebensgefährdet" />
					<Option code="C17" term="moribund" />
				</Auswahl>
				<Auswahl code="C30" term="Versorgungssituation">
					<Option code="C31" term="unabhängig" />
					<Option code="C32" term="Pflege zuhause" />
					<Option code="C33" term="Pflege in Instutition" />
				</Auswahl>
				<Auswahl code="C40" term="Antikoagulanzienmedikation (vor dem Ereignis)" typ="mehrfach">
					<Option code="C41" term="TZ-Aggregationshemmer" />
					<Option code="C42" term="VitK-Antagonist" />
					<Option code="C43" term="DOAK" />
					<Option code="C44" term="Heparin" />
					<Sonstiges code="C45" term="Sonstige" />
				</Auswahl>
				<Auswahl code="C1L" term="Ersthelfermaßnahmen (Laien)" typ="einfach">
					<leer code="C1S" term="keine" />
					<Option code="C1Z" term="suffizient" />
					<Option code="C26" term="insuffizient" />
				</Auswahl>
				<Frage code="C2D" term="First Responder vor Ort" typ="j_opt">
					<wenn-ja>
						<Feld code="C2K" term="ggf. Uhrzeit des Eintreffens" typ="Zeit" />
					</wenn-ja>
				</Frage>
				<!--
				<Auswahl code="AUTO" term="First Responder">
				<Option code="AUTO" term="vor Ort">
				<Zusatz>
				<Feld code="AUTO" term="ggf. Uhrzeit des Eintreffens" typ="Zeit"/>
				</Zusatz>
				</Option>
				</Auswahl>
				-->
				<Frage code="C2R" term="Besiedelung mit multiresistenten Keimen (MRSA, MRSE, ESBL etc) vorbekannt" typ="j_opt">
					<wenn-ja>
						<Auswahl code="C2Y" typ="mehrfach">
							<Option code="C35" term="abgedeckt" />
							<Option code="C3C" term="offen" />
						</Auswahl>
					</wenn-ja>
				</Frage>
				<!--
				<Auswahl code="AUTO">
				<Option code="AUTO" term="Besiedelung mit multiresistenten Keimen (MRSA, MRSE, ESBL etc) vorbekannt">
				<Zusatz>
				<Auswahl code="AUTO" typ="mehrfach">
				<Option code="AUTO" term="abgedeckt"/>
				<Option code="AUTO" term="offen"/>
				</Auswahl>
				</Zusatz>
				</Option>
				</Auswahl>
				-->
			</Formular>
		</Abschnitt>
		<Abschnitt code="D01">
			<Titel>
				Erstbefunde
